name:       isocline
version:    1.0.9
github:     "daanx/isocline"
license:    MIT
author:     Daan Leijen
maintainer: daan@effp.org
synopsis:   A portable alternative to GNU Readline
category:   console

extra-source-files:
  - haskell/readme.md
  - src/*.c
  - src/*.h
  - include/*.h

description: 
  "![logo](https://raw.githubusercontent.com/daanx/isocline/main/doc/isocline-inline.svg) 
  A Haskell wrapper around the [Isocline C library](https://github.com/daanx/isocline#readme) 
  which can provide an alternative to GNU Readline.
  (The Isocline library is included whole and there are no runtime dependencies).  
  
  Please see the [readme](https://github.com/daanx/isocline/haskell#readme) on GitHub for more information."

dependencies:
  - base >= 3.0 && < 5      
  - bytestring
  - text

library:
  source-dirs:
    - haskell
  c-sources:
    - src/isocline.c

executables:
  example:
    main: Example.hs
    source-dirs: test
    dependencies: 
      - isocline

tests:
  test-example:
    main: Example.hs
    source-dirs: test
    dependencies: 
      - isocline      
